### ISSUE TITLE
LFWA simulation params

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu-workshop#11]
Am I correct in assuming that, by Tuesday afternoon, the participants will all have (at least) a run with the parameters from slide `17` of `03_Input_and_Manual.pdf` and the following plugins activated: `EnergyHistogram`, `PhaseSpace`, `PNG`, `HDF5`, `Checkpoint`?

I am asking because from the slides and notebooks, I found the following paths
- `"/bigdata/hplsim/scratch/huebl/lwfa_001/"`
- `"/bigdata/hplsim/scratch/huebl/lwfa_003/"`
- `"/home/starke88/tmp/pic_sims/scan_0001/sim_0005/run/"`
which I would like to replace with
- `/bigdata/hplsim/external/bercea20/runs/lwfa_001` etc
so I need to know what run(s) is(are) needed.

**Comment by n01r** [comment]
I think a good example is `/bigdata/hplsim/scratch/ziegle18`.
It's one of the previous participants' workshop data directories.

There we had:

| Day | File / Directory |
|-------|---------------------|
| Monday | `lwfa_001`-`..002` |
| Tuesday | `lwfa_003`-`..005` |
| Wednesday | `04_Python_Postprocessing_Exercise.ipynb` <br> `foil_flag000`-`..003` <br> `05_Python_Postprocessing_OpenPMD.ipynb ` <br> `source_labs_001`-`..002` |
| Thursday | `06_Analyze_FoilLCT.ipynb` <br> `foil_ionization` <br> `foil_radiation` <br> `07_Complex_Targets_and_Ionization.ipynb` <br> `08_inSituDataAnalysis_radiation_probes_tracers.ipynb` <br> `foil_radiation2` |
| Friday | `...` |

We did not introduce HDF5 before session 4 because we wanted to gradually add more and more plugins and make the example more and more detailed.

**Comment by berceanu** [comment]
I have no access to `/bigdata/hplsim/scratch/ziegle18`. I can access `/bigdata/hplsim/external/finn-o16/lwfa_X`, but only partially, ie. can't read `simOutput`, `stderr` or `stdout`. Could you perhaps copy them to `/bigdata/hplsim/external/bercea20/runs`?

**Comment by berceanu** [comment]
I tried re-running `lwfa_006a` and `lwfa_006c` and they both crashed with `splash::DCException`.

**Comment by ax3l** [comment]
Yes, we start simple in the first session just to run an unmodified example and then play around with it. Usually LWFA, but we let the users decide along the way for their preferences. We usually suggest LWFA first, later foil, as you noted above.

I wrote to Tim Ziegler (`ziegle18`) to copy his workshop output to your `/bigdata/hplsim/external/bercea20/`. He will create a `ziegle18/` dir inside with according read and write access for you.

**Comment by berceanu** [comment]
Still nothing so far.
@ax3l , perhaps you could copy `/bigdata/hplsim/scratch/huebl/lwfa_003/`?

**Comment by ax3l** [comment]
I pinged Tim again. The `lwfa_003` is likely just a totally regular LWFA example with few devices :)

**Comment by ax3l** [comment]
@berceanu Last workshop's data is now available for you under `/bigdata/hplsim/external/bercea20/ziegle18` :)

**Comment by berceanu** [comment]
> I pinged Tim again. The `lwfa_003` is likely just a totally regular LWFA example with few devices :)

Yes but somehow it fails when activating `hdf5` output. For exemple, re-running `/bigdata/hplsim/external/bercea20/ziegle18/ziegle18/lwfa_005` via `pic-create` + same `tbg` command crashes.

**Comment by PrometheusPi** [comment]
@berceanu Could you post the error message from picongpu (I assume it crashed in picongpu) - or better where did you run the simulation and can we access that directory?

**Comment by berceanu** [comment]
`/bigdata/hplsim/external/bercea20/runs/lwfa_006`
@PrometheusPi can you access it?

**Comment by PrometheusPi** [comment]
@berceanu thanks for sharing the path - most of it, I can access but `stderr`(and `stdout`) are still not accessible. Could you give me/us read access to these files please?

**Comment by berceanu** [comment]
I chmoded the whole thing :)

**Comment by berceanu** [comment]
I shared:
- `/bigdata/hplsim/external/bercea20/ziegle18/ziegle18/lwfa_005`, ran by Tim's on 2018-10-23 with `0.4.0`
- `/bigdata/hplsim/external/bercea20/runs/lwfa_006`, ran by me with `dev`.
- `/bigdata/hplsim/external/bercea20/runs/lwfa_007`, ran by me with `0.4.3`.

Steps to reproduce:
```console
$ echo $HOME
/home/bercea20
$ echo $SCRATCH
/bigdata/hplsim/external/bercea20
```
```console
$ . k80_picongpu.profile
$ pic-create /bigdata/hplsim/external/bercea20/ziegle18/ziegle18/lwfa_005/input $HOME/picInputs/lwfa_007
$ cd picInputs/lwfa_007/
$ pic-build
$ tbg -s -t -c etc/picongpu/8_new $SCRATCH/runs/lwfa_007
```

**Comment by psychocoderHPC** [comment]
```
$ tbg -s -t -c etc/picongpu/8_new $SCRATCH/runs/lwfa_007
```

This command is using the `k80.tpl` from the cloned input set ` /bigdata/hplsim/external/bercea20/ziegle18/ziegle18/lwfa_005`. Since the input set is from the version before we added the workaround for the [OpenMPI romio bug](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2857) @berceanu is running into the same bug.
