### ISSUE TITLE
data reduction slide

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu-workshop#12]
@ax3l , what's the idea behind this slide?

![data_reduction_slide](https://user-images.githubusercontent.com/4405658/52855696-dac14f00-312a-11e9-967d-0765c40ebe91.png)

**Comment by ax3l** [comment]
Several things, I could talk 15min about that slide ;-) Some values are also missing, e.g. data reduction ratio and throughput.

Also some ideas that I usually overlay: "brush and link", correlate, repeat.

Basically the ground idea is that LPA needs
- high resolution 3D3V simulations

but yet the analysis is operating on way smaller final data, so why store the whole 3D3V data and use PBytes of disk space?

Well, because today's workflow in science is about 70% of analysis/"plugins"/reduction per system which are standard (think: energy & phase space histograms), but 30% per scientific case need special coding / processing and therefore access to raw sim data (think: weird geometry, target, fancy laser, ...).

We want to (/must) move all of the analysis chain from file-based, prohibitively large and slow post-processing, over our live plugins with parameters, to live-codeable in situ processing -> projects: openPMD and openPMD-api (parallel! scriptable!), ADIOS2 staging methods.

Also, data reduction is a non-trivial HPC problem and needs performance modeling which can be demonstrated for each of the points on the slide as well: https://arxiv.org/abs/1706.00522

I know the description here is a bit brief but I am quite busy writing right now... :(
