### ISSUE TITLE
jupyter notebook service

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu-workshop#9]
I am going through the workshop workflow, in preparation for my presentation.

After logging in, one is greeted by the screen below
![start_notebook](https://user-images.githubusercontent.com/4405658/52587058-bcfd9c80-2e41-11e9-898e-b45e12b5d770.png)
What should be filled in at this point? I tried leaving the defaults, which got me to
![tree_lab](https://user-images.githubusercontent.com/4405658/52587059-c0912380-2e41-11e9-87a4-3d9753bbf3d9.png)
However, on this screen both `go to tree` and `go to lab` take me to invalid pages.

**Comment by n01r** [comment]
Yes, that is because there is yet no port-forwarding to your browser when you're outside the HZDR domain.
In order to get access from somewhere else you need to open a tunnel by yourself.
#### 1. Note down the port number that the notebook is sending data over on hypnos5
![01_no_tunnel_configured](https://user-images.githubusercontent.com/5416860/52642227-dbfc3d00-2eda-11e9-8a29-18fbfe71fdcf.png)
#### 2. Open an ssh tunnel via uts to hypnos5 and forward the local ports there, choosing on of your machine ports as the listening port
![02_open_tunnel](https://user-images.githubusercontent.com/5416860/52642310-0d750880-2edb-11e9-89d5-d93894f070e7.png)
#### 3. Go to your browser again and type `localhost:<port number>`
![03_put_in_port_number](https://user-images.githubusercontent.com/5416860/52642512-72c8f980-2edb-11e9-9ac9-96287d46564b.png)

That should fix it, right?

**Comment by n01r** [comment]
Sorry about the super light colors - I overdid it a bit with the lightening

**Comment by berceanu** [comment]
![jupyter_error](https://user-images.githubusercontent.com/4405658/52643713-45ce1400-2ee6-11e9-8504-49514cc01d03.png)

**Comment by berceanu** [comment]
SR.8513

**Comment by ax3l** [comment]
Following extra info:

you can modify the loaded python and environment in a file `$HOME/jupyter.profile`.

If you want to base stable on certain modules, we recommend filling it with:
```bash
module purge
module load python/3.6.2
module load cmake/3.10.1  # to do: update to 3.11.0 or newer
module load gcc/4.9.2
module load zlib/1.2.8
module load hdf5/1.8.14

# PIConGPU Python modules for post-processing
export PICSRC=${HOME}/src/picongpu
export PYTHONPATH=${PICSRC}/lib/python:${PYTHONPATH}
```

For a more complex setup one can also base this on anaconda without our modules, but the setup time is about one hour when I move fast, which we should skip for now.

**Comment by berceanu** [comment]
Fixed by SR.8513 and @n01r instructions.

**Comment by berceanu** [comment]
Can someone apply this patch to `/bigdata/hplsim/external/software/jupyter.profile`? Workshop users are expected to copy that file to their `$HOME`.
[jupyter_profile_patch.txt](https://github.com/ComputationalRadiationPhysics/picongpu-workshop/files/2868651/jupyter_profile_patch.txt)
